# Generated by Django 5.2.11 on 2026-02-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_respond_message_assignment_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='price',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='proposal',
            field=models.FileField(default='templates/assignment/proposal.txt', upload_to='uploads/'),
        ),
    ]
