# Generated by Django 5.2.11 on 2026-02-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_price_assignment_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='proposal',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
