# Generated by Django 5.2.11 on 2026-02-25 07:28

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='proposal',
            field=models.FileField(upload_to='uploads/', validators=[assignments.models.validate_assignment_file]),
        ),
    ]
