# Generated by Django 5.2.11 on 2026-02-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to='teacher_responses'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='respond_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
