# Generated by Django 5.2.11 on 2026-02-25 09:14

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignment_response_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to='teacher_responses', validators=[assignments.models.validate_assignment_file]),
        ),
    ]
